image: Visual Studio 2017

version: 0.5.0+{build}

environment:
  global:
    DEBUG: 6-mils:*
  matrix:
    - node_version: '12'
    - node_version: '10'
    - node_version: '8'

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:node_version

before_test:
  - npm --version
  - npm install

test_script:
  - npm test

build: off
