image: Visual Studio 2017

version: 0.5.0+{build}

environment:
  DEBUG: 6-mils:*
  matrix:
    - nodever: '12'
    - nodever: '10'
    - nodever: '8'

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodever

before_test:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
